<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>citrus</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(grammer|rule).*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*end</string>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>Citrus Grammar</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(require)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.special-method.citrus</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$|(?=#)</string>
			<key>name</key>
			<string>meta.require.citrus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(grammar)\s+((?:(::)?[A-Z]\w*)+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.begin.grammar.citrus</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.grammar.citrus</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.grammar.citrus</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\bend\b</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.end.grammar.citrus</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.grammar.citrus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.special-method.citrus</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.module.citrus</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.grammar.citrus</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(include)\s+((?:(::)?[A-Z]\w*)+)</string>
					<key>name</key>
					<string>meta.include.citrus</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(rule)\s+([a-zA-Z][a-zA-Z0-9_-]*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.begin.rule.citrus</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.rule.citrus</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.scope.rule.citrus</string>
					<key>end</key>
					<string>\bend\b</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.end.rule.citrus</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.rule.citrus</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regexp</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#character-class</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#dot</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#operator</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#super</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#rule-reference</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\{</string>
							<key>end</key>
							<string>\}</string>
							<key>name</key>
							<string>meta.embedded-ruby.citrus</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.ruby</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>character-class</key>
		<dict>
			<key>begin</key>
			<string>\[(?:\^?\])?</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.character-class.citrus</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>string.regexp.character-class.citrus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.citrus</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^[ \t]+)?(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.citrus</string>
		</dict>
		<key>dot</key>
		<dict>
			<key>match</key>
			<string>\.</string>
			<key>name</key>
			<string>constant.character.dot.citrus</string>
		</dict>
		<key>escaped_char</key>
		<dict>
			<key>match</key>
			<string>\\(?:[0-7]{1,3}|x[\da-fA-F]{1,2}|.)</string>
			<key>name</key>
			<string>constant.character.escape.citrus</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.citrus</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.citrus</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\d*)\*(\d*)</string>
					<key>name</key>
					<string>keyword.operator.other.citrus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\+|\?</string>
					<key>name</key>
					<string>keyword.operator.other.citrus</string>
				</dict>
			</array>
		</dict>
		<key>regexp</key>
		<dict>
			<key>begin</key>
			<string>((/))(?![*+{}?])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.citrus</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.citrus</string>
				</dict>
			</dict>
			<key>end</key>
			<string>((/[eimnosux]*))</string>
			<key>name</key>
			<string>string.regexp.citrus</string>
		</dict>
		<key>rule-reference</key>
		<dict>
			<key>match</key>
			<string>[a-zA-Z][a-zA-Z0-9_-]*</string>
			<key>name</key>
			<string>variable.other.citrus</string>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.citrus</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.citrus</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.citrus</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\'|\\\\</string>
							<key>name</key>
							<string>constant.character.escape.citrus</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.citrus</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.citrus</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.citrus</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>super</key>
		<dict>
			<key>match</key>
			<string>\bsuper\b</string>
			<key>name</key>
			<string>variable.language.citrus</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.citrus</string>
	<key>uuid</key>
	<string>201BC9C8-9303-47F8-9C4D-4EC27778DABD</string>
</dict>
</plist>
